### PR TITLE
Location based url hash permalink

### PR DESCRIPTION
**Pull request by Yukaii**
ref: #161

### Screenshots

disfactory-permalink

### TODOs

- [x] Fix ts
- [x] geolocation check
- ~~share button~~ 先不做

### CODE REVIEW

**Comment by stegben** [comment]
水

**Comment by Yukaii** [comment]
- [ ] 調換一下經緯度

**Comment by Yukaii** [comment]
先來合

**Comment by aelcenganda** [comment]
對不起，軟體好像還是會緯度寫前面？根據 yellowsoar 在 slack 裡面的說法


*--*
*簡韻真 / **Yun-Chen Chien *
g0v 參與者 / Nobody in g0v.tw <http://g0v.asia>
@aelcenganda on Twitter <https://twitter.com/aelcenganda>, Medium
<https://medium.com/@aelcenganda>, LinkedIn
<https://www.linkedin.com/in/aelcenganda/> and Facebook
<https://www.facebook.com/aelcenganda>
+886-937-458-069 on phone, WhatsApp, Telegram and Signal

**Pull request merged**
